### PR TITLE
Workflow build Docker image with arm64,amd64

### LINKED ISSUE #117: [Feature Request] arm64/armv7 docker/ghcr build
Would it be possible to edit the ghcr.io docker build to add arm64/armv7 support (for raspberry pi)? I have been using this build by eblabs which has arm support https://hub.docker.com/r/eblabs/cabernet/tags for a while now, and I think I may be having issues related to using an outdated docker image (about a year old now). 

I would try to edit the image myself to add arm64/armv7 support but I have no idea where to begin

### PR DESCRIPTION
**Pull request by Generator**
### Summary

- Fixes #117 
- Github Workflow to build docker images for amd64(x86-64) and arm64
- Github Workflow docker image with tags: latest, master, version, other branches (only dev)
- Added entrypoint.sh, start with custom UserID/GroupID 
- Run Cabernet as user
- Rework docker-compose
- Rework dockerfile
- Smaller x86-64 image (old 397MB, new 280MB)
- Reformatted README.md with better instructions for docker
- Reformatted docker-compose.yml

### Notes
You can use single Dockerfile, other files are reluctant.
However is possible to update the app within the container, is recommended for the user update the image instead.
Won't be possible to build for arm(32bit) due to [python cryptography system requirements](https://cryptography.io/en/latest/installation/#supported-platforms).
Additional files or directories to include on docker must be added to .dockerignore (ex: ``!filename.ext`` ``!somedir/``)
Docker images tested on x86-64 and arm64 (Raspberry Pi 4)

### CODE REVIEW

**Comment by cookieisland** [comment]
Only mapping the data directory and not the entire cabernet folder will cause problems.  The recommendation is to map the entire cabernet source folder to /app.  There are multiple reasons for this. Here are two:

1) Docker does not like a container to change/update itself unless the changes are in a docker volume or in a bind mount. The update/upgrade process built into cabernet modfies not just /app/data but also /app/plugins_ext, /app/lib etc.  Eventually these updates will cause the filesystem where docker is installed to run out of disk space as /var/lib/docker/overlay2 keeps growing and growing with every cabernet update. See this link for more on what happens if a docker image updates itself https://buisteven.medium.com/debugging-docker-overlay2-out-of-space-d1edc2ea412f  This was discussed some time ago and here is a link to that discussion: https://github.com/cabernetwork/cabernet/issues/60#issuecomment-1496470833

2) When you pull a new cabernet docker image you will lose your installed plugins because they are not in /app/data. They are in /app/plugins_ext.  If you do not map the entire source tree you will need to reinstall your plugins every time you pull a new docker image (and this will make #1 above worse because you are again updating the docker image)

I notice you also removed the mapping for /root/.cabernet/key.txt from the docker compose file.   This will cause problems for people who have turned on encryption.  This file is where the cryptography key is stored when your turn on the cabernet "use_encryption" option.  If this file is not mapped via a docker volume or bind mount it will be lost when a new docker image of cabernet is pulled. When you lose this key, cabernet will fail because will not be able to decrypt the encrypted data after the docker image pull.

**Comment by rocky4546** [comment]
Agree with cookieisland.  encryption key MUST be mounted in a volume and not be lost.  If it is lost, anything encrypted would not be useable. Also, the entire Cabernet source must also be mounted in a volume due to the way Docker handles updates.

**Comment by rocky4546** [comment]
Also, the hostname called "your-ip" is required to have a space.  I do not care if its called your ip, my ip, their ip or ip address, it must contain a space.  This is to handle those with no brain cells that think "your-ip" is an actual hostname.  I had a issue written up on this and now require a space in the hostname area.

**Comment by cookieisland** [comment]
Note that when you switch users from root to cabernet that will likely change the location of the encryption key.txt file.  People using the current docker container which runs as the root have their encryption key located at "/root/.cabernet/key.txt"  
However when they switch to your proposed docker container their encryption key will then be located in the home directory for the user 'cabernet' which I beleieve would be "/home/cabernet/.cabernet/key.txt".  This will cause problems/support issues if the user doesn't modify their docker compose file to remap their key.txt file to the correct new location when they transition from the current docker image to your proposed new docker image.

**Comment by rocky4546** [comment]
Looks really good.  Thanks for the updates.  Still reviewing the changes, but have one question.  The app does not support adhoc updates to the Cabernet source.  As an example, if someone were to overlay a different version of cabernet, the app does not try to fix or patch the database or config file to support the version extracted.  This means docker upgrades would not apply the patches for the upgrade unless docker also changed the maintenance flag in the config.ini to True.  Then the system would apply any patches required to run on the new version.

How did you keep the webui from doing the upgrade?  And, how does the software respond?  Does it throw exceptions?

**Comment by rocky4546** [comment]
Applying PR to dev branch for testing.

**Pull request merged**
